FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY apps/frontend/package.json ./apps/frontend/

RUN corepack enable && yarn install

COPY apps/frontend ./apps/frontend

EXPOSE 5173

CMD ["yarn", "workspace", "frontend", "dev", "--host"]