FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY domain/package.json ./domain/
COPY apps/backend/package.json ./apps/backend/

RUN corepack enable && yarn install

COPY domain ./domain
COPY apps/backend ./apps/backend

EXPOSE 3000

CMD ["yarn", "run", "tsx", "apps/backend/src/server.ts"]